### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'POS' 

### ISSUE THREAD

**Issue by julieaorjuela** [AntoineHo/HapPy#5]
hello,
 
I'm trying to use happy using these commands:
```export PATH=$PATH:/home/orjuela/sambamba/bin/
happy coverage --threads 6 --outdir=SMART_HAPPY SMARTDENOVO_minimap2mapping.bam
happy estimate --size=600000000 --outstats=SMART_happy_estimate -P SMART_HAPPY/SMARTDENOVO_minimap2mapping.bam
```
but i'm having a lot of warnings and an error does not allow me to calculate stats...  can you please help me ? 

```
Processing reference #2052 (utg33780)
Processing reference #2053 (utg34895)
/home/orjuela/.local/lib/python3.7/site-packages/happy/plot.py:10: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/home/orjuela/.local/bin/happy", line 5, in <module>
    from happy.Hap import main
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/Hap.py", line 27, in <module>
    import happy.commands as commands
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/commands.py", line 17, in <module>
    import happy.coverage as happyc
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/coverage.py", line 8, in <module>
    from happy.utils import *
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/utils.py", line 10, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python-3.7.2/lib/python3.7/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/local/python-3.7.2/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 17, in <module>
    line for line in traceback.format_stack()

  mpl.use("Agg")
Running coverage module.
# Hap.py coverage
Input alignment file:	SMARTDENOVO_minimap2mapping.bam
Output directory:	SMART_HAPPY
Number of threads:	6
===============================================================================

2021-03-05 22:00:08: Starting sambamba depth...

2021-03-06 03:26:41: Reading coverage file...

2021-03-06 03:32:14: Finished!
/home/orjuela/.local/lib/python3.7/site-packages/happy/plot.py:10: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/home/orjuela/.local/bin/happy", line 5, in <module>
    from happy.Hap import main
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/Hap.py", line 27, in <module>
    import happy.commands as commands
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/commands.py", line 17, in <module>
    import happy.coverage as happyc
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/coverage.py", line 8, in <module>
    from happy.utils import *
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/utils.py", line 10, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python-3.7.2/lib/python3.7/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/local/python-3.7.2/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 17, in <module>
    line for line in traceback.format_stack()


  mpl.use("Agg")
# Hap.py estimate
Coverage histogram:	SMART_HAPPY/SMARTDENOVO_minimap2mapping.bam.cov
Output file:	SMART_happy_estimate

===============================================================================


2021-03-06 03:32:25: Reading histogram!
Traceback (most recent call last):
  File "/home/orjuela/.local/bin/happy", line 8, in <module>
    sys.exit(main())
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/Hap.py", line 50, in main
    command.execute()
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/commands.py", line 91, in execute
    self.args["--outstats"],
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/estimate.py", line 33, in estimate_haploidy
    freqs = [int(line.split()[1]) for line in open(HIST, "r")][1:-1]
  File "/home/orjuela/.local/lib/python3.7/site-packages/happy/estimate.py", line 33, in <listcomp>
    freqs = [int(line.split()[1]) for line in open(HIST, "r")][1:-1]
ValueError: invalid literal for int() with base 10: 'POS' 
```
Thanks !

Julie

**Comment by AntoineHo** [comment]
Hello,

The first errors are probably due to issues in version compatibility with matplotlib (maybe OS related). It should not be a problem to get the statistics but might be an issue for some visualisation of the histogram curves.

The second error is probably a simple input file issue, if the coverage command terminated without problems (as seems to be the case here excluding matplotlib compatibility issues), then you should use for the estimation a file called `SMARTDENOVO_minimap2mapping.bam.hist` and not `.cov`.

Then you should be able to run it smoothly. This file simply contains two columns and should look like:
```
0    1826743
1    648593
2    520353
...
```
Note that the `estimate` command requires thresholds for the peak area computation which you can set by looking at the histogram curve.

Cheers,

Antoine

**Comment by julieaorjuela** [comment]
Thanks @AntoineHo , I use hist and not cov to estimate haploidy and it works ! nice plots for estimate function.
Julie

**Comment by AntoineHo** [comment]
No problem,

Thanks!
